### ISSUE TITLE
IT Budget validation error

### ISSUE THREAD

**Issue by SriramAvasarala** [ombegov/ITDB-schema#281]
Name: Sriram Avasarala
Organization: Treasury
Urgency: Medium
Description of Issue: We are getting following IT Budget validation error with manual XML submission. The error is repeated for every UII in the xml file. I have sent the XML file to MBX.OMB.ITDASHBOARD@OMB.eop.gov.

alert000214-ITP: Only Type 04 Funding Transfer Investments should report PY amounts within the Internal Services Cost Pool.
alert000214-ITP: Only Type 04 Funding Transfer Investments should report CY amounts within the Internal Services Cost Pool.
alert000214-ITP: Only Type 04 Funding Transfer Investments should report BY amounts within the Internal Services Cost Pool.

**Comment by elliotyoon202** [comment]
The node needs to be removed for all non-Type 04s rather than setting it to zero. All of the following should be removed.

<CostPool>
          <CostPoolCategory>Total Internal Services Amount</CostPoolCategory>
          <PriorYearAmount>0</PriorYearAmount>
          <CurrentYearAmount>0</CurrentYearAmount>
          <BudgetYearAmount>0</BudgetYearAmount>
 </CostPool>

**Comment by courtneycorwin** [comment]
Hi - Oracle's updated the map files to accommodate this, but would you consider allowing zeros and only applying the validation to values larger than zero?

**Comment by elliotyoon202** [comment]
Unfortuneately, "zero" is a different construct than "not allowed" and they are treated differently in the code,

**Comment by jeremiah-tcg** [comment]
We deployed 2018.09A to UAT which included the change identified in our last comment. Please us know if the issue is now resolved.

**Comment by courtneycorwin** [comment]
This is all set for us, thanks!

**Comment by rydougherty** [comment]
Hi Jerimiah, can we reopen this issue? I see the validation you amended now allows for sending zero in the following manner: `<update-ITBudget-ext:PriorYearAmount>0</update-ITBudget-ext:PriorYearAmount>`. However, if I send zero in the six decimal format to match the reporting in millions requirement, I still receive the the validation error: `<update-ITBudget-ext:PriorYearAmount>0.000000</update-ITBudget-ext:PriorYearAmount>`

> `<response-ITBudget-ext:ResponseLogDescription>000214-ITP: Only Type 04 Funding Transfer Investments should report PY amounts within the Internal Services Cost Pool.</response-ITBudget-ext:ResponseLogDescription>`

**Comment by jeremiah-tcg** [comment]
Reopened as requested.

**Comment by jeremiah-tcg** [comment]
Hi Ryan,
We deployed 2018.09B to UAT and production that included a fix for this. Please let me know if we can close this issue.
Regards, 
Jeremiah

**Comment by rydougherty** [comment]
Hi Jeremiah- we have verified the fix. Glad you got this in prior to the start of the AITPS window.

**Comment by jeremiah-tcg** [comment]
Excellent! Thanks Ryan! I will close the issue now.
